name: graphql_play_env
channels:
  - conda-forge
  - defaults
dependencies:
  - autopep8>=1.5.4
  - black>=20.8b1
  - fastapi>=0.62.0
  - flake8>=3.8.4
  - graphene>=2.1.8
  - graphene-sqlalchemy>=2.3.0
  - jedi>=0.17.2
  - pip>=20.3.3
  - pytest>=6.2.1
  - pytest-cov>=2.10.1
  - python>=3.9.1
  - rope>=0.18.0
  - sqlalchemy>=1.3.22
  - uvicorn>=0.13.2
  - yapf>=0.30.0
  - pip:
    - ariadne>=0.12.0
